# Generated by Django 3.1.1 on 2020-11-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=5)),
                ('room_type', models.CharField(choices=[('KS', 'King Smoking'), ('KNS', 'King Non-Smoking')], default=None, max_length=3)),
                ('check_out', models.BooleanField(default=True)),
                ('room_clean', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'room',
            },
        ),
    ]
